<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16858" started-at="2017-07-24T09:08:02Z" finished-at="2017-07-24T09:08:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16858" started-at="2017-07-24T09:08:02Z" finished-at="2017-07-24T09:08:19Z">
      <class name="com.test.TestCase.KFGL.TC_wy">
        <test-method status="PASS" signature="start()[pri:0, instance:com.test.TestCase.KFGL.TC_wy@204f30ec]" name="start" is-config="true" duration-ms="3216" started-at="2017-07-24T17:08:03Z" finished-at="2017-07-24T17:08:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="wy()[pri:0, instance:com.test.TestCase.KFGL.TC_wy@204f30ec]" name="wy" duration-ms="13431" started-at="2017-07-24T17:08:06Z" finished-at="2017-07-24T17:08:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [更改测试内容] but found [再次更改备注]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [更改测试内容] but found [再次更改备注]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.test.PageAction.Login.BasePage.AssertEqualsFromExcel(BasePage.java:175)
	at com.test.PageAction.KFGL.wy_Page.wy_ViewDetail(wy_Page.java:67)
	at com.test.TestCase.KFGL.TC_wy.wy(TC_wy.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wy -->
      </class> <!-- com.test.TestCase.KFGL.TC_wy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
